export {default as Splash } from './splash/splash'
export {default as TopNewsList} from './topNews/topNewsList/topNewsList'
export {default as NewNewsList} from './newNews/newNewsList/newNewsList'
export {default as BestNewsList} from './bestNews/bestNewsList/bestNewsList'
export {default as AllProcess} from './allProcess/allProcess'